---
# tasks file for roles/ansible-ejbca-crypto-token

- name: Query keys on {% if key_item.0.crypto_token_name is defined %}"{{ key_item.0.crypto_token_name }}"{% else %}"{{ key_item.0.caname }}"{% endif %}
  command: >
    {{ ejbca_sh }} cryptotoken listkeys --token {% if key_item.0.crypto_token_name is defined %}"{{ key_item.0.crypto_token_name }}"{% else %}"{{ key_item.0.caname }}"{% endif %}
  no_log: true
  become: yes
  become_user: "{{ ejbca_user }}"
  register: check_cryptoToken_keys
  changed_when: 'key_item.1.key_label not in check_cryptoToken_keys.stdout'
  failed_when: false

- debug:
    msg: "Failed to query keys on the crypto token: {{ check_cryptoToken_keys.stdout }}"
  when: 
    - check_cryptoToken_keys.rc >= 2
  failed_when: true

- name: Generate key if it does not exist for {% if key_item.0.crypto_token_name is defined %}{{ key_item.0.crypto_token_name }}{% else %}{{ key_item.0.caname }}{% endif %} - {{ key_item.1.key_label }}:{{ key_item.1.key_size }}
  command: >
    {{ ejbca_sh }} cryptotoken generatekey 
    --token {% if key_item.0.crypto_token_name is defined %}"{{ key_item.0.crypto_token_name }}"{% else %}"{{ key_item.0.caname }}"{% endif %} 
    --alias {{ key_item.1.key_label }} 
    --keyspec {{ key_item.1.key_size }}
  become: yes
  become_user: "{{ ejbca_user }}"
  register: add_key_to_cryptotoken
  failed_when: false
  when: check_cryptoToken_keys.changed

- debug:
    msg: "Failed to create the key: {{ add_key_to_cryptotoken.stdout }}"
  when: 
    - add_key_to_cryptotoken.rc >= 2
  failed_when: true


