---
# defaults file for ansible-ejbca-pkc11-client

ejbca_group: wildfly
ejbca_user: wildfly

use_softhsm: true

softhsm_gen_hsm_slots:
  - slot_name: Management_CA_SLOT
    slot_so_pin: "{{ encrypted_mgmtca_so_token_pin | default('foo123') }}" 
    slot_pin: "{{ encrypted_mgmtca_token_pin | default('foo123') }}"
  - slot_name: Root_CA_SLOT
    slot_so_pin: "{{ encrypted_rootca_so_token_pin | default('foo123') }}"
    slot_pin: "{{ encrypted_rootca_token_pin | default('foo123') }}"
  - slot_name: Root2_CA_SLOT
    slot_so_pin: "{{ encrypted_rootca2_so_token_pin | default('foo123') }}"
    slot_pin: "{{ encrypted_rootca2_token_pin | default('foo123') }}"
  - slot_name: Sub_CA_SLOT
    slot_so_pin: "{{ encrypted_subca_so_token_pin | default('foo123') }}"
    slot_pin: "{{ encrypted_subca_token_pin | default('foo123') }}"
  - slot_name: Sub2_CA_SLOT
    slot_so_pin: "{{ encrypted_subca2_so_token_pin | default('foo123') }}"
    slot_pin: "{{ encrypted_subca2_token_pin | default('foo123') }}"
  - slot_name: Sub3_CA_SLOT
    slot_so_pin: "{{ encrypted_subca3_so_token_pin | default('foo123') }}"
    slot_pin: "{{ encrypted_subca3_token_pin | default('foo123') }}"
  - slot_name:  DB_Protect_SLOT
    slot_so_pin: "{{ encrypted_databaseprotection_so_token_pin | default('foo123') }}"
    slot_pin: "{{ encrypted_databaseprotection_token_pin | default('foo123') }}"
  - slot_name: KeyBinding_SLOT
    slot_so_pin: "{{ encrypted_peerkeybind_so_token_pin | default('foo123') }}"
    slot_pin: "{{ encrypted_peerKeyBinding_token_pin | default('foo123') }}"
  - slot_name: POLICY1_CA_SLOT
    slot_so_pin: "{{ encrypted_policyca1_so_token_pin | default('foo123') }}" 
    slot_pin: "{{ encrypted_policyca1_token_pin | default('foo123') }}"
  - slot_name: POLICY2_CA_SLOT
    slot_so_pin: "{{ encrypted_policyca2_so_token_pin | default('foo123') }}" 
    slot_pin: "{{ encrypted_policyca2_token_pin | default('foo123') }}"
  - slot_name: LDAP_AUTH_SLOT
    slot_so_pin: "{{ encrypted_ldap_auth_so_token_pin | default('foo123') }}" 
    slot_pin: "{{ encrypted_ldap_auth_token_pin | default('foo123') }}"
  - slot_name: AZURE_AUTH_SLOT
    slot_so_pin: "{{ encrypted_azure_auth_so_token_pin | default('foo123') }}" 
    slot_pin: "{{ encrypted_azure_auth_token_pin | default('foo123') }}"

# Cloudhsm variables
use_liquidsec: false
cloudhsm_home: /opt/cloudhsm
cloudhsm_client_url: https://s3.amazonaws.com/cloudhsmv2-software/CloudHsmClient/EL7/
cloudhsm_client_file: cloudhsm-client-latest.el7.x86_64.rpm
cloudhsm_dest: /var/tmp
cloudhsm_pcks11_url: https://s3.amazonaws.com/cloudhsmv2-software/CloudHsmClient/EL7/
cloudhsm_pkcs11_file: cloudhsm-client-pkcs11-latest.el7.x86_64.rpm
cloudhsm_service: cloudhsm-client
cloudhsm_ip: '172.16.2.209'
hsm_config_files: '{{ playbook_dir }}/hsm_config_files'
customerCA_cert: customerCA.crt
cloudhsm_tar_file: cloudhsm-May11-2020.tar.gz
liquidsec: cloudhsm/lib/libliquidsec_pkcs11.so
