---
# defaults file for wildfly

wildfly_manage_user: true
ejbca_ra_group: ejbcara
ejbca_ra_user: ejbcara

wildfly_manage_java_pkg: false
wildfly_manage_firewall: false
wildfly_manage_standalone_data: true
wildfly_manage_service: true
wildfly_remove_download_file: true

wildfly_version: 19.1.0.Final
wildfly_major_v: "{{ wildfly_version.partition('.')[0] }}"


wildfly_base_download_url: http://download.jboss.org/wildfly
wildfly_name: wildfly-{{ wildfly_version }}
wildfly_download_validate_certs: "yes"
wildfly_download_file: "{{ wildfly_name }}.tar.gz"
wildfly_download_url: "{{ wildfly_base_download_url }}/{{ wildfly_version }}/\
                       {{ wildfly_download_file }}"
wildfly_download_dir: /tmp

wildfly_install_dir: /opt
wildfly_home: "{{ wildfly_install_dir }}/wildfly"
wildfly_dir: "{{ wildfly_install_dir }}/{{ wildfly_name }}"
wildfly_dir_mode: '0750'
wildfly_create_symlink: true
wildfly_symlink_dir: "{{ wildfly_install_dir }}/wildfly"

wildfly_init_src_path: "{{ 'docs/contrib/scripts' if wildfly_major_v | version_compare('10', '>=') else 'bin' }}"

wildfly_java_xms: 2048m
wildfly_java_xmx: 2048m

wildfly_console_log_dir: "/var/log/wildfly"
wildfly_console_log_file: "console.log"
wildfly_console_log: "{{ wildfly_console_log_dir }}/\
                      {{ wildfly_console_log_file }}"

wildfly_conf_dir: /etc/wildfly
wildfly_standalone_config_file: standalone.xml
wildfly_standalone_config_path: "{{ wildfly_dir }}/standalone/configuration/\
                                 {{ wildfly_standalone_config_file }}"
wildfly_startup_wait: ''
wildfly_shutdown_wait: ''

wildfly_node_name: ''
wildfly_init_dir: /etc/init.d
wildfly_systemd_dir: /usr/lib/systemd/system

wildfly_file_perms:
  - find "{{ wildfly_symlink_dir }}"/ -type f -name *.xml -print -exec chmod 660 {} \;
  - find "{{ wildfly_symlink_dir }}"/ -type f -name *.jar -print -exec chmod 660 {} \;

wildfly_bind_address: 0.0.0.0
wildfly_management_bind_address: 0.0.0.0
wildfly_manage_http_port: 9990
wildfly_manage_https_port: 9993
wildfly_http_port: 8080
wildfly_https_port: 8443
wildfly_bind_address_unsecure: ''
wildfly_messaging_group_address: ''

wildfly_management_users: []
wildfly_app_users: []

wildfly_enable_ssl: no
wildfly_keystore_name: my.jks
wildfly_keystore_path: "{{ wildfly_dir }}/standalone/configuration/\
                        {{ wildfly_keystore_name }}"
wildfly_keystore_alias: my
wildfly_keystore_password: "secret"
wildfly_key_password: "secret"
wildfly_application_ssl_identity: '
    <server-identities>
        <ssl>
            <keystore path="{{ wildfly_keystore_name }}"
             relative-to="jboss.server.config.dir"
             alias="{{ wildfly_keystore_alias }}"
             keystore-password="{{ wildfly_keystore_password }}"
             key-password="{{ wildfly_key_password }}"/>
        </ssl>
    </server-identities>'
wildfly_https_listener: '
    <https-listener name="https-server" socket-binding="https"
     security-realm="ManagementRealm"/>'
