---
# defaults file for roles/ansible-ejbca-cnfdump-stage

ejbca_root_dir: /opt
ejbca_home: "{{ ejbca_root_dir }}/ejbca"
ejbca_sh: "{{ ejbca_home }}/bin/ejbca.sh"
wildfly_install_dir: /opt
wildfly_home: "{{ wildfly_install_dir }}/wildfly"
ejbca_group: wildfly
ejbca_user: wildfly

configdump_dir_structure:
  - "{{ ejbca_home }}/dump/dump1/certificate-profiles"
  - "{{ ejbca_home }}/dump/dump1/extended-key-usage"
  - "{{ ejbca_home }}/dump/dump1/certification-authorities"
  - "{{ ejbca_home }}/dump/dump2/certificate-profiles"
  - "{{ ejbca_home }}/dump/dump2/certification-authorities"
  - "{{ ejbca_home }}/dump/dump2/end-entity-profiles"
  - "{{ ejbca_home }}/dump/dump2/services"
  - "{{ ejbca_home }}/dump/dump2/custom-certificate-extensions"
  - "{{ ejbca_home }}/dump/dump3/admin-roles"
  - "{{ ejbca_home }}/dump/dump3/certificate-profiles"
  - "{{ ejbca_home }}/dump/dump3/end-entity-profiles"
  - "{{ ejbca_home }}/dump/dump3/services"
  - "{{ ejbca_home }}/dump/dump3/publishers"
  - "{{ ejbca_home }}/dump/dump3/acme-config"
  - "{{ ejbca_home }}/dump/dump3/est-config"
  - "{{ ejbca_home }}/dump/dump3/scep-config"
  - "{{ ejbca_home }}/dump/va/services"
  - "{{ ejbca_home }}/dump/va/publishers"  
  - "{{ ejbca_home }}/dump/ra/admin-roles" 
  
configdump_files:
  - src: 'cp-RootCA-G1.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump1/certificate-profiles/RootCA-{{ organizationNameShort }}-G1.yaml'
  - src: 'cp-managementCA.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump1/certificate-profiles/ManagementCA.yaml'
  - src: 'extended-key-usages.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump1/extended-key-usage/extended-key-usages.yaml'
    # Files for the 2nd dump import
  - src: 'cp-SubCA-G1.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump2/certificate-profiles/SubCA-{{ organizationNameShort }}-G1.yaml'
  - src: 'cp-HashiCorp-SubCA-G1.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump2/certificate-profiles/HashiCorp-SubCA-G1.yaml'
  - src: 'cp-tlsPeerConnector.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump2/certificate-profiles/tlsPeerConnector.yaml'
  - src: 'ee-tlsPeerConnMgmt.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump2/end-entity-profiles/tlsPeerConnMgmt.yaml'
  - src: 'service-DailyCRLUpdate.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump2/services/DailyCRLUpdate.yaml'
  - src: 'service-HSM_Keepalive.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump2/services/HSM_Keepalive.yaml'
  - src: 'ext-id-piv-NACI.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump2/custom-certificate-extensions/id-piv-NACI.yaml'
  - src: 'ext-certTempInfo.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump2/custom-certificate-extensions/certTempInfo.yaml'
    # Files for the 3rd dump import
  - src: 'global-acme-configuration.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/acme-config/global-acme-configuration.yaml'
  - src: 'acme-alias-1.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/acme-config/acme-alias-1.yaml'
  - src: 'ee-AdminInternal.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/end-entity-profiles/AdminInternal.yaml'
  - src: 'ee-tlsServerAcme.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/end-entity-profiles/tlsServerAcme.yaml'
  - src: 'ee-tlsServerOrg.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/end-entity-profiles/tlsServer{{ organizationNameShort }}.yaml'
  - src: 'ee-ocspSigner.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/end-entity-profiles/ocspSigner.yaml'
  - src: 'ee-tlsServerMgmt.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/end-entity-profiles/tlsServerMgmt.yaml'
  - src: 'ee-userAuthentication.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/end-entity-profiles/userAuthentication.yaml'
  - src: 'ee-userDigitalSignature.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/end-entity-profiles/userDigitalSignature.yaml'
  - src: 'ee-userEncryption.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/end-entity-profiles/userEncryption.yaml'
  - src: 'ee-intuneDevice.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/end-entity-profiles/intuneDevice.yaml'
  - src: 'ee-tlsServerApprovalOrg.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/end-entity-profiles/tlsServerApproval{{ organizationNameShort }}.yaml'
  - src: 'ee-codeSigning.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/end-entity-profiles/codeSigning.yaml'
  - src: 'ee-domainController.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/end-entity-profiles/domainController.yaml'
  - src: 'ee-estDevice.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/end-entity-profiles/estDevice.yaml'
  - src: 'ee-remoteDesktopAuth.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/end-entity-profiles/remoteDesktopAuth.yaml'
  - src: 'ee-scepDevice.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/end-entity-profiles/scepDevice.yaml'
  - src: 'ee-signersOrg.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/end-entity-profiles/signers{{ organizationNameShort }}.yaml'
  - src: 'ee-timeStampingAuthority.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/end-entity-profiles/timeStampingAuthority.yaml'
  - src: 'ee-vpnFirewall.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/end-entity-profiles/vpnFirewall.yaml'
  - src: 'ee-workstations.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/end-entity-profiles/workstations.yaml'
  - src: 'cp-tlsServerMgmtCA.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/tlsServerMgmtCA.yaml'
  - src: 'cp-AdminNoCDPMgmtCA.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/AdminNoCDPMgmtCA.yaml'
  - src: 'cp-tlsClientAuth.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/tlsClientAuth.yaml'
  - src: 'cp-tlsServerAuth.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/tlsServerAuth.yaml'
  - src: 'cp-tlsServerClientAuth.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/tlsServerClientAuth.yaml'
  - src: 'cp-adminMgmtCA.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/adminMgmtCA.yaml'
  - src: 'cp-DigitalSignature-2048.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/DigitalSignature-2048.yaml'
  - src: 'cp-Authentication-2048.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/Authentication-2048.yaml'
  - src: 'cp-Encryption-2048.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/Encryption-2048.yaml'
  - src: 'cp-tlsServerAuthAcme90d.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/tlsServerAuthAcme90d.yaml'
  - src: 'cp-ocspSigner.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/ocspSigner.yaml'
  - src: 'cp-ocspSignerEcc-15d.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/ocspSignerEcc-15d.yaml'
  - src: 'cp-intuneClientAuth-1y.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/intuneClientAuth-1y.yaml'
  - src: 'cp-tlsServerAuthApproval.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/tlsServerAuthApproval.yaml'
  - src: 'cp-tlsClientAuthApproval.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/tlsClientAuthApproval.yaml'
  - src: 'cp-tlsServerClientAuthApproval.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/tlsServerClientAuthApproval.yaml'
  - src: 'cp-signerCodeSigning.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/signerCodeSigning.yaml'
  - src: 'cp-signerTimeStampAuthority.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/signerTimeStampAuthority.yaml'
  - src: 'cp-signerPdf-3y.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/signerPdf-3y.yaml'
  - src: 'cp-signer-3y.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/signer-3y.yaml'
  - src: 'cp-domainController.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/domainController.yaml'
  - src: 'cp-remoteDesktopAuth.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/remoteDesktopAuth.yaml'
  - src: 'cp-vpnFirewall.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/vpnFirewall.yaml'
  - src: 'cp-workstation.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/certificate-profiles/workstation.yaml'
  - src: 'est-device.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/est-config/device.yam'
  - src: 'est-firewall.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/est-config/firewall.yaml'
  - src: 'scep-device.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/scep-config/device.yaml'
  - src: 'scep-firewall.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/scep-config/firewall.yaml'
  - src: 'role-userEnrollment.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/admin-roles/role-userEnrollment.yaml'
  - src: 'role-ra-est.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/admin-roles/role-ra-est.yaml'
  - src: 'role-ra-vault.yaml.j2'
    dest: '{{ ejbca_home }}/dump/dump3/admin-roles/role-ra-vault.yaml'
    # Files for External VA
  - src: 'service-ocspService.yaml.j2'
    dest: '{{ ejbca_home }}/dump/va/services/ocspService.yaml'
    # Files for External RA
  - src: 'role-ra-peer-connection.yaml.j2'
    dest: '{{ ejbca_home }}/dump/ra/admin-roles/role-ra-peer-connection.yaml'
