---

- hosts: ejbcaCaServers
  become: yes
  become_method: sudo
  pre_tasks:
    - include_vars: deployment_info/internal_ca_subdorinate_vars.yml
  vars:
    # Use this option to generate keys for the Authkey Bindings, configure the AuthKey Binding, configure Peering.
    # Import certificate profiles, end entity profiles, publishers, and roles for the RA peer and other roles wantes
    deploy_post_ca_config: true
    # Map in List Dictionaires for the configdump directory structure and configdump files
    configdump_directory_structure: "{{ authkeybind_configdump_dir_structure }}"
    configdump_import_files: "{{ authkeybind_configdump_files }}"
  roles:
    - ansible-ejbca-ca-ee
