---

- name: Stage Okay Repo GPG Key
  copy:
    src: RPM-GPG-KEY-okayinc
    dest: /etc/pki/rpm-gpg/
    owner: root
    group: root
    mode: 0644
  when: 
    - (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8") or
      (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

- name: Import Okay Repo key from a file
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-okayinc
  when: 
    - (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8") or
      (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

- name: Install SoftHSM CentOS/RHEL 8
  dnf:
    name: "{{ softhsm_8 }}"
    state: present
    #disable_gpg_check: yes
  when: 
    - (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8") or
      (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

- name: Install SoftHSM CentOS/RHEL 7
  yum:
    name: "{{ softhsm_7 }}"
    state: present
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7") or
        (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7") 

- name: Set permissions on softhsm lib directory
  file:
    path: /var/lib/softhsm
    state: directory
    recurse: yes
    mode: 0750
    owner: "{{ ejbca_user }}"
    group: "{{ ejbca_group }}"

- name: Check SoftHSM Slots
  shell: >
    softhsm2-util --show-slots | grep {{ item.slot_name }}
  register: show_hsm_slots
  loop: "{{ softhsm_gen_hsm_slots }}"
  changed_when: show_hsm_slots.rc != 0
  failed_when: false
  no_log: true

- name: Create SoftHSM slots
  command: >
    softhsm2-util 
    --init-token 
    --free 
    --label {{ item.item.slot_name }} 
    --so-pin {{ item.item.slot_so_pin }} 
    --pin {{ item.item.slot_pin }}
  become: yes  
  become_user: "{{ ejbca_user }}" 
  loop: "{{ show_hsm_slots.results }}"
  no_log: true
  register: create_hsm_slots
  when: item.changed
