---
# defaults file for ansible-ejbca-certreq-cli
ejbca_csr_dir_output: "{{ playbook_dir }}/ejbcaCSR"
ejbca_root_dir: /opt
ejbca_home: "{{ ejbca_root_dir }}/ejbca"
ejbca_sh: "{{ ejbca_home }}/bin/ejbca.sh"
wildfly_install_dir: /opt
wildfly_home: "{{ wildfly_install_dir }}/wildfly"
ejbca_group: wildfly
ejbca_user: wildfly

identity_batch_output_dir: /var/tmp
organizationName: Solitude
organizationNameShort: "{{ organizationName }}"

identity_info:
  dn: 'ou=Devices,ou=Solitude,o=Skyrim'
  name: ra01.solitude.skyrim
  full_dn: "C={{ countryName }},O={{ organizationName }},OU=Devices,CN=ra01.solitude.skyrim"
  username: ra_httpd_tls
  password: "{{ encrypted_httpd_identity_password | default('foo123') }}"
  altname: "dNSName=ra01.solitude.skyrim"
  certprofile: tlsServerClientAuth
  eeprofile: "tlsServer{{ organizationNameShort }}"
  caname: "{{ organizationNameShort }}-Sub-CA"
  token: PEM
  useType: ra

cert_files:
  - src: "{{ identity_batch_output_dir }}/pem/{{ identity_info.id_name }}.pem"     
    dest: "{{ ejbca_csr_dir_output }}/{{ identity_info.id_name }}.crt"
  - src: "{{ identity_batch_output_dir }}/pem/{{ identity_info.id_name }}-Key.pem"
    dest: "{{ ejbca_csr_dir_output }}/{{ identity_info.id_name }}.key"
  - src: "{{ identity_batch_output_dir }}/pem/{{ identity_info.id_name }}-CA.pem"
    dest: "{{ ejbca_csr_dir_output }}/trusted-ca.crt"


