---

- name: Check if Configdump already exists
  stat:
    path: "{{ ejbca_home }}/dist/configdump/configdump.jar"
  register: cfgdump_exists

- name: Build Configdump
  command: "/usr/bin/ant -q configdump"
  args:
    chdir: "{{ ejbca_home }}"
    creates: "{{ ejbca_home }}/dist/configdump/configdump.jar"
  become_user: "{{ ejbca_user }}"
  become_method: sudo
  when: not cfgdump_exists.stat.exists

- name: Create Dump file structure for Dump1
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ ejbca_user }}"
    group: "{{  ejbca_group }}"
  loop: "{{ configdump_dir_structure_1 }}"

- name: Stage RA Dump template files for Dump1
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ejbca_user }}"
    group: "{{ ejbca_group }}"
    mode: 0664
  loop: "{{ configdump_ra_files_dump1 }}"
  when: ejbca_type == "RA"

- name: Stage VA Dump template files for Dump1
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ejbca_user }}"
    group: "{{ ejbca_group }}"
    mode: 0664
  loop: "{{ configdump_va_files_dump1 }}"
  when: ejbca_type == "VA"

- name: Import Dump files for Dump1
  command: "./configdump.sh import  --ignore-errors -l {{ ejbca_home }}/dump/dump1 --overwrite update --non-interactive continue"
  args:
    chdir: "{{ ejbca_home }}/dist/configdump"
  become: yes 
  become_user: "{{ ejbca_user }}"

