---
# defaults file for ansible-ejbca-certreq-cli
ejbca_csr_dir_output: "{{ playbook_dir }}/ejbcaCSR"
ejbca_root_dir: /opt
ejbca_home: "{{ ejbca_root_dir }}/ejbca"
ejbca_sh: "{{ ejbca_home }}/bin/ejbca.sh"
wildfly_install_dir: /opt
wildfly_home: "{{ wildfly_install_dir }}/wildfly"
ejbca_group: wildfly
ejbca_user: wildfly

identity_batch_output_dir: /var/tmp
organizationName: Solitude

identity_info:
  - dn: 'ou=Devices,ou=Solitude,o=Skyrim'
    name: sign01.solitude.skyrim
    full_dn: "cn=sign01.solitude.skyrim,ou=Devices,ou=Solitude,o=Skyrim"
    username: ra_httpd_tls
    password: "{{ encrypted_httpd_signsrv_identity_password | default('foo123') }}"
    altname: "dNSName=sign01.solitude.skyrim"
    certprofile: tlsServerClientAuth
    eeprofile: "tlsServer{{ organizationName }}"
    caname: "{{ organizationName }}-Sub-CA"
    token: PEM
    useType: signserver
