---

- name: Query crypto tokens
  command: "{{ ejbca_home }}/bin/ejbca.sh cryptotoken list"
  no_log: true
  become: yes
  become_user: "{{ ejbca_user }}"
  register: cryptoToken_list
  changed_when: false

#- name: Debug
#  debug:
#    var: item

- name: Create cryptotoken for {{ item.caname }}
  command: >
    {{ ejbca_home }}/bin/ejbca.sh cryptotoken create 
    --token {{ item.caname }} 
    --pin {{ item.tokenpass }} 
    --autoactivate {{ item.cryptotoken_enable_auto_activate }} 
    --type {% if "soft" == item.tokentype %}"SoftCryptoToken"{% elif "org.cesecore.keys.token.PKCS11CryptoToken" == item.tokentype or "PKCS11CryptoToken" == item.tokentype %}"PKCS11CryptoToken" 
    --lib "{{ hsm_shared_library }}" 
    --slotlabel "{{ item.slot_identifier_value }}"
    --slotlabeltype "{{ item.slot_identifier_type }}"{% endif %}
  no_log: true
  become: yes
  become_user: "{{ ejbca_user }}"
  register: add_cryptotoken
  failed_when: add_cryptotoken.rc >= 2
  #changed_when: keybinding_cryptotoken.rc == 0
  when: item.caname not in cryptoToken_list.stdout
