---
galaxy_info:
  author: Robert de Bock
  role_name: hostname
  description: Install dependencies and configure the hostname on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.8

  platforms:
    - name: Amazon
      versions:
        - 2018.03
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - bionic

  galaxy_tags:
    - hostname
    - centos
    - redhat

dependencies:
  - robertdebock.reboot
