---
# defaults file for ansible-ss-httpd
ejbca_csr_dir_output: "{{ playbook_dir }}/ejbcaCSR"
signsvr_root_dir: /opt
signsvr_home: "{{ signsvr_root_dir }}/ejbca"
wildfly_install_dir: /opt
wildfly_home: "{{ wildfly_install_dir }}/wildfly"
signsrv_group: wildfly
signsrv_user: wildfly

add_mgmt_ca: true

httpd_identity_info:
  id_name: sign01.solitude.skyrim

httpd_packages:
  - httpd
  - mod_ssl

httpd_conf_files_8:
  - src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  - src: ssl-ss.conf.j2
    dest: /etc/httpd/conf.d/ssl.conf
  - src: 00-base.conf.j2
    dest: /etc/httpd/conf.modules.d/00-base.conf
  - src: 00-dav.conf.j2
    dest: /etc/httpd/conf.modules.d/00-dav.conf
  - src: 00-lua.conf.j2
    dest: /etc/httpd/conf.modules.d/00-lua.conf
  - src: 00-proxy.conf.j2
    dest: /etc/httpd/conf.modules.d/00-proxy.conf
  - src: 01-cgi.conf.j2
    dest: /etc/httpd/conf.modules.d/01-cgi.conf
  - src: 80.conf.j2
    dest: /etc/httpd/conf.d/80.conf

httpd_conf_files_7:
  - src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  - src: ssl7-ss.conf.j2
    dest: /etc/httpd/conf.d/ssl.conf
  - src: 80.conf.j2
    dest: /etc/httpd/conf.d/80.conf

httpd_cert_files:
  - src: "{{ ejbca_csr_dir_output }}/{{ httpd_identity_info.id_name }}.crt"
    dest: "/etc/pki/tls/certs/{{ httpd_identity_info.id_name }}.crt"
  - src: "{{ ejbca_csr_dir_output }}/{{ httpd_identity_info.id_name }}.key"
    dest: "/etc/pki/tls/private/{{ httpd_identity_info.id_name }}.key"
  - src: "{{ ejbca_csr_dir_output }}/{{ httpd_identity_info.httpd_ca_cert_file }}.crt"
    dest: "/etc/pki/tls/certs/trusted-ca.crt"
